// netlify/functions/api.js
// Proxies frontend requests to the actual Python backend.
// Prevents CORS/HTTPS Mixed Content blockages.

exports.handler = async (event, context) => {
  // Read target backend URL from environment variables, defaulting to local dev port
  const backendUrl = process.env.BACKEND_URL || 'http://localhost:8000';
  
  // Extract route and query string
  const path = event.path.replace('/.netlify/functions/api', '');
  const queryString = event.rawQuery || '';
  const targetUrl = `${backendUrl}${path}${queryString ? '?' + queryString : ''}`;

  console.log(`Proxying: ${event.httpMethod} ${event.path} -> ${targetUrl}`);

  try {
    const headers = { ...event.headers };
    // Remove headers that should be regenerated by fetch
    delete headers.host;
    delete headers['x-nf-client-connection-ip'];
    delete headers['client-ip'];
    
    if (event.body && !headers['content-type']) {
      headers['content-type'] = 'application/json';
    }

    const options = {
      method: event.httpMethod,
      headers: headers,
    };

    if (event.body && ['POST', 'PUT', 'PATCH'].includes(event.httpMethod)) {
      options.body = event.body;
    }

    const response = await fetch(targetUrl, options);
    const contentType = response.headers.get('content-type') || '';
    
    let responseBody;
    if (contentType.includes('application/json')) {
      responseBody = JSON.stringify(await response.json());
    } else {
      responseBody = await response.text();
    }

    // Forward response headers while dropping transfer encoding headers
    const responseHeaders = {};
    response.headers.forEach((value, key) => {
      if (!['content-encoding', 'transfer-encoding'].includes(key.toLowerCase())) {
        responseHeaders[key] = value;
      }
    });

    return {
      statusCode: response.status,
      headers: responseHeaders,
      body: responseBody,
    };
  } catch (error) {
    console.error('Error proxying request:', error);
    return {
      statusCode: 502,
      body: JSON.stringify({
        error: 'Bad Gateway',
        message: 'Could not reach the Python backend. Verify the BACKEND_URL environment variable on Netlify.',
        details: error.message
      }),
      headers: { 'Content-Type': 'application/json' }
    };
  }
};
